# Generated by Django 6.0.6 on 2026-07-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_passwordsetuptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PasswordSetupToken',
        ),
    ]
