# Generated by Django 6.0.6 on 2026-07-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_user_must_change_password_delete_passwordsetuptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
